# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/spundsteif/',
                'doc_host': 'https://PAYEUR.github.io',
                'git_url': 'https://github.com/PAYEUR/spundsteif/tree/master/',
                'lib_path': 'spundsteif'},
  'syms': { 'spundsteif.None': {},
            'spundsteif.catman': {},
            'spundsteif.core': {},
            'spundsteif.deformations': {},
            'spundsteif.inclinometers': {},
            'spundsteif.plaxis': {},
            'spundsteif.plaxis_linear': {},
            'spundsteif.pressures': {},
            'spundsteif.sensors': {},
            'spundsteif.strain_gauges': {}}}
