# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"__construct_INFO__": "01_sensors.ipynb",
         "__construct_list_DATA__": "01_sensors.ipynb",
         "read_files": "01_sensors.ipynb",
         "__dates_sorted__": "01_sensors.ipynb",
         "__ind_chrono_order__": "01_sensors.ipynb",
         "sort_chrono": "01_sensors.ipynb",
         "__elements_vides__": "01_sensors.ipynb",
         "traitement_elements_vides": "01_sensors.ipynb",
         "__condition_DATA__": "01_sensors.ipynb",
         "list_names_channels": "01_sensors.ipynb",
         "extract_T0": "01_sensors.ipynb",
         "construction_list_df_messung": "01_sensors.ipynb",
         "concat_df_messung": "01_sensors.ipynb",
         "traitement_colonnes_zeit": "01_sensors.ipynb",
         "__clean_name__": "01_sensors.ipynb",
         "traitement_colonnes_names": "01_sensors.ipynb",
         "conversion_float": "01_sensors.ipynb",
         "change_overhead_values": "01_sensors.ipynb",
         "downsample": "01_sensors.ipynb",
         "get_automatic_data": "01_sensors.ipynb",
         "define_index": "01_sensors.ipynb",
         "get_manual_data": "03_pressures.ipynb",
         "df_to_m": "01_sensors.ipynb",
         "get_data": "01_sensors.ipynb",
         "construct_df_csv": "03_pressures.ipynb",
         "drop_columns": "02_inclinometers.ipynb",
         "update_type_date": "02_inclinometers.ipynb",
         "rename_columns": "02_inclinometers.ipynb",
         "add_column_up": "02_inclinometers.ipynb",
         "df_multiindex": "02_inclinometers.ipynb",
         "compute_average_A_B": "02_inclinometers.ipynb",
         "compute_rotations": "02_inclinometers.ipynb",
         "__deformee__": "02_inclinometers.ipynb",
         "column_integration": "02_inclinometers.ipynb",
         "get_null_measure_date": "02_inclinometers.ipynb",
         "column_deformee_relative": "02_inclinometers.ipynb",
         "run_computation_inklino": "02_inclinometers.ipynb",
         "extract_df_datetube": "02_inclinometers.ipynb",
         "build_fig_defo": "02_inclinometers.ipynb",
         "clean": "03_pressures.ipynb",
         "merge_piezo_excavation": "03_pressures.ipynb",
         "clean_manual_df": "03_pressures.ipynb",
         "merge_manual_automatic": "03_pressures.ipynb"}

modules = ["sensors.py",
           "inclinometers.py",
           "pressures.py"]

doc_url = "https://PAYEUR.github.io/spundsteif/"

git_url = "https://github.com/PAYEUR/spundsteif/tree/master/"

def custom_doc_links(name): return None
