# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"construct_df_csv": "02_inclinometers.ipynb",
         "drop_columns": "02_inclinometers.ipynb",
         "update_type_date": "02_inclinometers.ipynb",
         "rename_columns": "02_inclinometers.ipynb",
         "add_column_up": "02_inclinometers.ipynb",
         "df_multiindex": "02_inclinometers.ipynb",
         "compute_average_A_B": "02_inclinometers.ipynb",
         "compute_rotations": "02_inclinometers.ipynb",
         "__deformee__": "02_inclinometers.ipynb",
         "column_integration": "02_inclinometers.ipynb",
         "get_zero_measure_date": "02_inclinometers.ipynb",
         "column_deformee_relative": "02_inclinometers.ipynb",
         "run_computation_inklino": "02_inclinometers.ipynb",
         "extract_df_datetube": "02_inclinometers.ipynb",
         "build_fig_defo": "02_inclinometers.ipynb"}

modules = ["inclinometers.py",
           "catman.py",
           "plaxis_linear.py",
           "plaxis.py",
           "None.py"]

doc_url = "https://PAYEUR.github.io/spundsteif/"

git_url = "https://github.com/PAYEUR/spundsteif/tree/master/"

def custom_doc_links(name): return None
