# AUTOGENERATED! DO NOT EDIT! File to edit: 04_deformations.ipynb (unless otherwise specified).

__all__ = ['clean']

# Cell
import pandas as pd
import numpy
import io
import csv
from datetime import datetime

from google.colab import files

from copy import copy

from datetime import timedelta
from datetime import datetime

import plotly.express as px
import plotly.graph_objects as go

import numpy as np

from spundsteif import sensors

# Cell
def clean(df):

  #TODO

  return df