# AUTOGENERATED! DO NOT EDIT! File to edit: 04_deformations.ipynb (unless otherwise specified).

__all__ = ['relative_defo', 'patch_sensors', 'get_deformations']

# Cell
import pandas as pd
import numpy
import io
import csv
from datetime import datetime

from google.colab import files

from copy import copy

from datetime import timedelta, date, timedelta

import plotly.express as px
import plotly.graph_objects as go

import numpy as np

from spundsteif import sensors

# Cell
from .inclinometers import get_zero_measure_date

def relative_defo(df, start_date):

  date_0 = get_zero_measure_date(df.index, start_date)

  measure_0 = df.loc[df.index == date_0]

  df = df - measure_0.to_numpy()

  df.loc[df.index < date_0] = np.nan

  return df

# Cell
def patch_sensors(df):
  disf_sensors = ['W11', 'W21', 'W32']

  #TODO code something clever...
  df = df.drop(columns=disf_sensors)

  return df

# Cell
# TODO: make sure zero measure date is OK
def get_deformations(df):

  df = clean(df)
  df = relative_defo(df, date(2021, 7, 18))
  df = patch_sensors(df)

  return df