# AUTOGENERATED! DO NOT EDIT! File to edit: 08_plaxis_polynomial.ipynb (unless otherwise specified).

__all__ = []

# Cell
import pandas as pd
import numpy as np
import io
import os
import csv
from datetime import datetime, date, timedelta

from google.colab import files

from copy import copy

import plotly.express as px
import plotly.graph_objects as go
import matplotlib.pyplot as plt

from sklearn import linear_model

import re

from spundsteif import inclinometers # we need also our own libraries